export  const Constant  ={
    // "rightmanage",
    // "usermanage",
    // "rolemanage",
    // "groupmanage",
    // "elementmanage",
    // "apimanage",
    // "rulemanage",
    // "entitymanage",
    adduserbtn: "adduserbtn",
    viewuserlink: "viewuserlink",
    editavatarlink: "editavatarlink",
    edituserlink: "edituserlink",
    deleteuserlink: "deleteuserlink",
    addrolebtn: "addrolebtn",
    editrolelink: "editrolelink",
    deleterolelink: "deleterolelink",
    addgroupbtn: "addgroupbtn",
    editgroupbtn: "editgroupbtn",
    deletegroupbtn: "deletegroupbtn",
    addelementbtn: "addelementbtn",
    editelementbtn: "editelementbtn",
    deleteelementbtn: "deleteelementbtn",
    addapibtn: "addapibtn",
    deleteapilink: "deleteapilink",
    editapilink: "editapilink",
    addrulegroupbtn: "addrulegroupbtn",
    editrulegroup: "editrulegroup",
    deleterulegrouplink: "deleterulegrouplink",
    addentitybtn: "addentitybtn",
    editentitylink: "editentitylink",
    deletedatalink: "deletedatalink",
    clearallbufferbtn:"clearallbuffer",
    clearbufferlink:"clearbuffer",
    delkafkadel:"delkafka",
    alltasklink:'alltask',
    unziplink:'unzip',
    sendatalink:'sendata',
    downloadlink:'download',
    AllBatchTask:"AllBatchTask",
    ViewTaskProcess:'ViewTaskProcess'
    // "test",
    // "testdata",
    // "addtestdatabtn",
    // "edittestdatalink"
}